import { Header } from "@/components/header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter} w-full min-h-screen mx-auto relative`}>
        <Image
          src="/lights.png"
          alt="Lights"
          width={1280}
          height={1280}
          objectFit="contain"
          className="fixed right-0 top-0 z-50 pointer-events-none"
        />
        <Toaster position="bottom-right" />
        <div className="flex w-full border-b border-zinc-900">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
